INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (1, "Aerospatiale (Nord) 262", "D2", "262");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (2, "Aerospatiale (Sud Aviation) Se.210 Caravelle", "CRV", "S210");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (3, "Aerospatiale SN.601 Corvette", "DC", "S601");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (4, "Aerospatiale/Alenia ATR 42-300", "AT4", "AT43");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (5, "Aerospatiale/Alenia ATR 42-500", "AT5", "AT45");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (6, "Aerospatiale/Alenia ATR 42-600", "ATR", "AT46");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (7, "Aerospatiale/Alenia ATR 72", "AT7", "AT72");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (8, "Airbus A300", "AB3", "A30B");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (9, "Airbus A300-600", "AB6", "A306");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (10, "Airbus A300-600ST Super Transporter / Beluga", "ABB", "A3ST");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (11, "Airbus A310", "310", "A310");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (12, "Airbus A318", "318", "A318");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (13, "Airbus A319", "319", "A319");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (14, "Airbus A319neo", "31", "A19");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (15, "Airbus A320", "320", "A320");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (16, "Airbus A320neo", "32", "A20");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (17, "Airbus A321", "321", "A321");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (18, "Airbus A321neo", "32Q", "A21");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (19, "Airbus A330", "330", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (20, "Airbus A330-200", "332", "A332");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (21, "Airbus A330-300", "333", "A333");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (22, "Airbus A330-700 Beluga XL", "", "A337");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (23, "Airbus A330-800neo", "338", "A338");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (24, "Airbus A330-900neo", "339", "A339");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (25, "Airbus A340", "340", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (26, "Airbus A340-200", "342", "A342");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (27, "Airbus A340-300", "343", "A343");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (28, "Airbus A340-500", "345", "A345");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (29, "Airbus A340-600", "346", "A346");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (30, "Airbus A350", "350", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (31, "Airbus A350-1000", "351", "A35K");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (32, "Airbus A350-900", "359", "A359");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (33, "Airbus A380", "380", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (34, "Airbus A380-800", "388", "A388");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (35, "Antonov AN-12", "ANF", "AN12");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (36, "Antonov AN-124 Ruslan", "A4F", "A124");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (37, "Antonov AN-140", "A40", "A140");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (38, "Antonov An-148", "A81", "A148");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (39, "Antonov An-158", "A58", "A158");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (40, "Antonov An-225 Mriya", "A25", "A225");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (41, "Antonov AN-24", "AN4", "AN24");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (42, "Antonov AN-26", "A26", "AN26");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (43, "Antonov AN-28", "A28", "AN28");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (44, "Antonov AN-30", "A30", "AN30");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (45, "Antonov AN-32", "A32", "AN32");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (46, "Antonov AN-72", "AN7", "AN72");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (47, "Avro RJ100", "AR1", "RJ1H");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (48, "Avro RJ70", "AR7", "RJ70");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (49, "Avro RJ85", "AR8", "RJ85");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (50, "BAe 146", "146", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (51, "BAe 146-100", "141", "B461");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (52, "BAe 146-200", "142", "B462");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (53, "BAe 146-300", "143", "B463");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (54, "Beechcraft 1900", "BEH", "B190");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (55, "Beechcraft Baron", "", "BE58");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (56, "Beechcraft Baron / 55 Baron", "", "BE55");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (57, "Bell 212", "BH2", "B212");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (58, "Boeing 707", "703", "B703");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (59, "Boeing 717", "717", "B712");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (60, "Boeing 720B", "B72", "B720");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (61, "Boeing 727", "727", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (62, "Boeing 727-100", "721", "B721");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (63, "Boeing 727-200", "722", "B722");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (64, "Boeing 737", "737", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (65, "Boeing 737 MAX 10", "7MJ", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (66, "Boeing 737 MAX 7", "7M7", "B37M");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (67, "Boeing 737 MAX 8", "7M8", "B38M");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (68, "Boeing 737 MAX 9", "7M9", "B39M");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (69, "Boeing 737-200", "732", "B732");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (70, "Boeing 737-300", "733", "B733");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (71, "Boeing 737-400", "734", "B734");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (72, "Boeing 737-500", "735", "B735");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (73, "Boeing 737-600", "736", "B736");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (74, "Boeing 737-700", "73G", "B737");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (75, "Boeing 737-800", "738", "B738");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (76, "Boeing 737-900", "739", "B739");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (77, "Boeing 747", "747", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (78, "Boeing 747 LCF Dreamlifter", "74B", "BLCF");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (79, "Boeing 747-100", "741", "B741");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (80, "Boeing 747-200", "742", "B742");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (81, "Boeing 747-300", "743", "B743");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (82, "Boeing 747-400", "744", "B744");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (83, "Boeing 747-400D", "74J", "B74D");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (84, "Boeing 747-8", "748", "B748");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (85, "Boeing 747SP", "74L", "B74S");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (86, "Boeing 747SR", "74R", "B74R");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (87, "Boeing 757", "757", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (88, "Boeing 757-200", "752", "B752");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (89, "Boeing 757-300", "753", "B753");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (90, "Boeing 767", "767", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (91, "Boeing 767-200", "762", "B762");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (92, "Boeing 767-300", "763", "B763");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (93, "Boeing 767-400", "764", "B764");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (94, "Boeing 777", "777", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (95, "Boeing 777-200", "772", "B772");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (96, "Boeing 777-200LR", "77L", "B77L");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (97, "Boeing 777-300", "773", "B773");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (98, "Boeing 777-300ER", "77W", "B77W");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (99, "Boeing 777-8", "778", "B778");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (100, "Boeing 777-9", "779", "B779");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (101, "Boeing 787", "787", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (102, "Boeing 787-10", "78J", "B78X");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (103, "Boeing 787-8", "788", "B788");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (104, "Boeing 787-9", "789", "B789");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (105, "Bombardier 415", "", "CL2T");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (106, "Bombardier BD-100 Challenger 300", "", "CL30");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (107, "Bombardier CS100", "CS1", "BCS1");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (108, "Bombardier CS300", "CS3", "BCS3");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (109, "Bombardier Global Express", "CCX", "GLEX");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (110, "British Aerospace (BAC) One Eleven", "B11", "BA11");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (111, "British Aerospace 125 series / Hawker/Raytheon 700/800/800XP/850/900", "H25", "H25B");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (112, "British Aerospace 125-1000 series / Hawker/Raytheon 1000", "H25", "H25C");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (113, "British Aerospace ATP", "ATP", "ATP");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (114, "British Aerospace Jetstream 31", "J31", "JS31");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (115, "British Aerospace Jetstream 32", "J32", "JS32");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (116, "British Aerospace Jetstream 41", "J41", "JS41");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (117, "Canadair Challenger", "CCJ", "CL60");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (118, "Canadair CL-44", "CL4", "CL44");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (119, "Canadair Regional Jet 100", "CR1", "CRJ1");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (120, "Canadair Regional Jet 1000", "CRK", "CRJX");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (121, "Canadair Regional Jet 200", "CR2", "CRJ2");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (122, "Canadair Regional Jet 700", "CR7", "CRJ7");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (123, "Canadair Regional Jet 900", "CR9", "CRJ9");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (124, "Cessna 152", "", "C152");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (125, "Cessna 172", "CN1", "C172");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (126, "Cessna 182 Skylane", "CN1", "C182");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (127, "Cessna 208 Caravan", "CN1", "C208");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (128, "Cessna 210 Centurion", "CN1", "C210");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (129, "Cessna Citation CJ3", "CNJ", "C25B");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (130, "Cessna Citation CJ4", "CNJ", "C25C");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (131, "Cessna Citation Excel", "CNJ", "C56X");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (132, "Cessna Citation I", "CNJ", "C500");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (133, "Cessna Citation II", "CNJ", "C550");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (134, "Cessna Citation Mustang", "CNJ", "C510");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (135, "Cessna Citation Sovereign", "CNJ", "C680");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (136, "Cessna Citation X", "CNJ", "C750");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (137, "COMAC C-919", "", "C919");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (138, "Concorde", "SSC", "CONC");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (139, "Dassault Falcon 2000", "D20", "F2TH");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (140, "Dassault Falcon 50", "DF3", "FA50");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (141, "Dassault Falcon 7X", "DF7", "FA7X");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (142, "Dassault Falcon 900", "DF9", "F900");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (143, "De Havilland Canada DHC-2 Beaver", "DHP", "DHC2");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (144, "De Havilland Canada DHC-2 Turbo-Beaver", "DHR", "DH2T");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (145, "De Havilland Canada DHC-3 Otter", "DHL", "DHC3");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (146, "De Havilland Canada DHC-4 Caribou", "DHC", "DHC4");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (147, "De Havilland Canada DHC-6 Twin Otter", "DHT", "DHC6");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (148, "De Havilland Canada DHC-7 Dash 7", "DH7", "DHC7");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (149, "De Havilland Canada DHC-8-100 Dash 8 / 8Q", "DH1", "DH8A");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (150, "De Havilland Canada DHC-8-200 Dash 8 / 8Q", "DH2", "DH8B");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (151, "De Havilland Canada DHC-8-300 Dash 8", "DH3", "DH8C");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (152, "De Havilland Canada DHC-8-400 Dash 8Q", "DH4", "DH8D");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (153, "De Havilland DH.104 Dove", "DHD", "DOVE");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (154, "De Havilland DH.114 Heron", "DHH", "HER");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (155, "Douglas DC-10", "D10", "DC10");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (156, "Douglas DC-3", "D3F", "DC3");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (157, "Douglas DC-6", "D6F", "DC6");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (158, "Douglas DC-8-50", "D8T", "DC85");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (159, "Douglas DC-8-62", "D8L", "DC86");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (160, "Douglas DC-8-72", "D8Q", "DC87");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (161, "Douglas DC-9-10", "D91", "DC91");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (162, "Douglas DC-9-20", "D92", "DC92");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (163, "Douglas DC-9-30", "D93", "DC93");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (164, "Douglas DC-9-40", "D94", "DC94");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (165, "Douglas DC-9-50", "D95", "DC95");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (166, "Embraer 170", "E70", "E170");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (167, "Embraer 175", "E75", "");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (168, "Embraer 175 (long wing)", "E7W", "E75L");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (169, "Embraer 175 (short wing)", "E7W", "E75S");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (170, "Embraer 190", "E90", "E190");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (171, "Embraer 195", "E95", "E195");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (172, "Embraer E190-E2", "290", "E290");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (173, "Embraer E195-E2", "295", "E295");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (174, "Embraer EMB 110 Bandeirante", "EMB", "E110");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (175, "Embraer EMB 120 Brasilia", "EM2", "E120");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (176, "Embraer Legacy 450", "", "E545");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (177, "Embraer Legacy 600", "ER3", "E35L");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (178, "Embraer Phenom 100", "EP1", "E50P");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (179, "Embraer Phenom 300", "EP3", "E55P");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (180, "Embraer RJ135", "ER3", "E135");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (181, "Embraer RJ140", "ERD", "E135");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (182, "Embraer RJ145", "ER4", "E145");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (183, "Fairchild Dornier 328JET", "FRJ", "J328");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (184, "Fairchild Dornier Do.228", "D28", "D228");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (185, "Fairchild Dornier Do.328", "D38", "D328");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (186, "Fokker 100", "100", "F100");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (187, "Fokker 50", "F50", "F50");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (188, "Fokker 70", "F70", "F70");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (189, "Fokker F27 Friendship", "F27", "F27");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (190, "Fokker F28 Fellowship", "F21", "F28");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (191, "Gulfstream Aerospace G-159 Gulfstream I", "GRS", "G159");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (192, "Gulfstream G280", "GR3", "G280");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (193, "Gulfstream G650", "GJ6", "GLF6");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (194, "Gulfstream IV", "GJ4", "GLF4");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (195, "Gulfstream V", "GJ5", "GLF5");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (196, "Gulfstream/Rockwell (Aero) Commander", "ACP", "AC68");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (197, "Gulfstream/Rockwell (Aero) Turbo Commander", "ACT", "AC90");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (198, "Harbin Yunshuji Y12", "YN2", "Y12");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (199, "Hawker Siddeley HS 748", "HS7", "A748");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (200, "Ilyushin IL114", "I14", "I114");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (201, "Ilyushin IL18", "IL8", "IL18");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (202, "Ilyushin IL62", "IL6", "IL62");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (203, "Ilyushin IL76", "IL7", "IL76");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (204, "Ilyushin IL86", "ILW", "IL86");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (205, "Ilyushin IL96", "I93", "IL96");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (206, "Learjet 35", "LRJ", "LJ35");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (207, "Learjet 60", "LRJ", "LJ60");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (208, "Lockheed L-1011 Tristar", "L10", "L101");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (209, "Lockheed L-1049 Super Constellation", "L49", "CONI");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (210, "Lockheed L-182 / 282 / 382 (L-100) Hercules", "LOH", "C130");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (211, "Lockheed L-188 Electra", "LOE", "L188");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (212, "McDonnell Douglas MD-11", "M11", "MD11");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (213, "McDonnell Douglas MD-81", "M81", "MD81");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (214, "McDonnell Douglas MD-82", "M82", "MD82");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (215, "McDonnell Douglas MD-83", "M83", "MD83");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (216, "McDonnell Douglas MD-87", "M87", "MD87");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (217, "McDonnell Douglas MD-88", "M88", "MD88");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (218, "McDonnell Douglas MD-90", "M90", "MD90");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (219, "NAMC YS-11", "YS1", "YS11");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (220, "Partenavia P.68", "PN6", "P68");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (221, "Pilatus Britten-Norman BN-2A Mk III Trislander", "BNT", "TRIS");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (222, "Pilatus Britten-Norman BN-2A/B Islander", "BNI", "BN2P");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (223, "Pilatus PC-12", "PL2", "PC12");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (224, "Pilatus PC-6 Turbo Porter", "PL6", "PC6T");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (225, "Piper PA-28 (above 200 hp)", "", "P28B");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (226, "Piper PA-28 (up to 180 hp)", "", "P28A");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (227, "Piper PA-31 Navajo", "PA2", "PA31");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (228, "Piper PA-44 Seminole", "", "PA44");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (229, "Piper PA-46", "PAG", "PA46");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (230, "Saab 2000", "S20", "SB20");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (231, "Saab SF340A/B", "SF3", "SF34");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (232, "Shorts SC-5 Belfast", "SHB", "BELF");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (233, "Shorts SC-7 Skyvan", "SHS", "SC7");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (234, "Shorts SD.330", "SH3", "SH33");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (235, "Shorts SD.360", "SH6", "SH36");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (236, "Sikorsky S-58T", "S58", "S58T");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (237, "Sikorsky S-61", "S61", "S61");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (238, "Sikorsky S-76", "S76", "S76");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (239, "Sikorsky S-92", "S92", "S92");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (240, "Sukhoi Superjet 100-95", "SU9", "SU95");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (241, "Tupolev Tu-134", "TU3", "T134");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (242, "Tupolev Tu-144", "", "T144");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (243, "Tupolev Tu-154", "TU5", "T154");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (244, "Tupolev Tu-204", "T20", "T204");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (245, "Yakovlev Yak-40", "YK4", "YK40");
INSERT INTO dw.Aircraft (idAircraft, aircraft_name, aircraft_IATA, aircraft_ICAO) VALUES (246, "Yakovlev Yak-42", "YK2", "YK42");
