INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (1, "Afghanistan", "AF", "AFG", 4, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (2, "Aland Islands", "AX", "ALA", 248, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (3, "Albania", "AL", "ALB", 8, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (4, "Algeria", "DZ", "DZA", 12, 1, 20);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (5, "American Samoa", "AS", "ASM", 16, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (6, "Andorra", "AD", "AND", 20, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (7, "Angola", "AO", "AGO", 24, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (8, "Anguilla", "AI", "AIA", 660, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (9, "Antarctica", "AQ", "ATA", 10, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (10, "Antigua and Barbuda", "AG", "ATG", 28, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (11, "Argentina", "AR", "ARG", 32, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (12, "Armenia", "AM", "ARM", 51, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (13, "Aruba", "AW", "ABW", 533, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (14, "Australia", "AU", "AUS", 36, 4, 10);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (15, "Austria", "AT", "AUT", 40, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (16, "Azerbaijan", "AZ", "AZE", 31, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (17, "Bahamas", "BS", "BHS", 44, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (18, "Bahrain", "BH", "BHR", 48, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (19, "Bangladesh", "BD", "BGD", 50, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (20, "Barbados", "BB", "BRB", 52, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (21, "Belarus", "BY", "BLR", 112, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (22, "Belgium", "BE", "BEL", 56, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (23, "Belize", "BZ", "BLZ", 84, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (24, "Benin", "BJ", "BEN", 204, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (25, "Bermuda", "BM", "BMU", 60, 3, 13);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (26, "Bhutan", "BT", "BTN", 64, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (27, "Bolivia (Plurinational State of)", "BO", "BOL", 68, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (28, "Bonaire Sint Eustatius and Saba", "BQ", "BES", 535, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (29, "Bosnia and Herzegovina", "BA", "BIH", 70, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (30, "Botswana", "BW", "BWA", 72, 1, 1);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (31, "Bouvet Island", "BV", "BVT", 74, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (32, "Brazil", "BR", "BRA", 76, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (33, "British Indian Ocean Territory", "IO", "IOT", 86, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (34, "Brunei Darussalam", "BN", "BRN", 96, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (35, "Bulgaria", "BG", "BGR", 100, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (36, "Burkina Faso", "BF", "BFA", 854, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (37, "Burundi", "BI", "BDI", 108, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (38, "Cambodia", "KH", "KHM", 116, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (39, "Cameroon", "CM", "CMR", 120, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (40, "Canada", "CA", "CAN", 124, 3, 13);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (41, "Cabo Verde", "CV", "CPV", 132, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (42, "Cayman Islands", "KY", "CYM", 136, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (43, "Central African Republic", "CF", "CAF", 140, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (44, "Chad", "TD", "TCD", 148, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (45, "Chile", "CL", "CHL", 152, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (46, "China", "CN", "CHN", 156, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (47, "Christmas Island", "CX", "CXR", 162, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (48, "Cocos (Keeling) Islands", "CC", "CCK", 166, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (49, "Colombia", "CO", "COL", 170, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (50, "Comoros", "KM", "COM", 174, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (51, "Congo", "CG", "COG", 178, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (52, "Congo (Democratic Republic of the)", "CD", "COD", 180, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (53, "Cook Islands", "CK", "COK", 184, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (54, "Costa Rica", "CR", "CRI", 188, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (55, "te d'Ivoire", "CI", "CIV", 384, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (56, "Croatia", "HR", "HRV", 191, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (57, "Cuba", "CU", "CUB", 192, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (58, "Curacao", "CW", "CUW", 531, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (59, "Cyprus", "CY", "CYP", 196, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (60, "Czech Republic", "CZ", "CZE", 203, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (61, "Denmark", "DK", "DNK", 208, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (62, "Djibouti", "DJ", "DJI", 262, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (63, "Dominica", "DM", "DMA", 212, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (64, "Dominican Republic", "DO", "DOM", 214, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (65, "Ecuador", "EC", "ECU", 218, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (66, "Egypt", "EG", "EGY", 818, 1, 20);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (67, "El Salvador", "SV", "SLV", 222, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (68, "Equatorial Guinea", "GQ", "GNQ", 226, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (69, "Eritrea", "ER", "ERI", 232, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (70, "Estonia", "EE", "EST", 233, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (71, "Ethiopia", "ET", "ETH", 231, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (72, "Falkland Islands (Malvinas)", "FK", "FLK", 238, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (73, "Faroe Islands", "FO", "FRO", 234, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (74, "Fiji", "FJ", "FJI", 242, 4, 22);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (75, "Finland", "FI", "FIN", 246, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (76, "France", "FR", "FRA", 250, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (77, "French Guiana", "GF", "GUF", 254, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (78, "French Polynesia", "PF", "PYF", 258, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (79, "French Southern Territories", "TF", "ATF", 260, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (80, "Gabon", "GA", "GAB", 266, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (81, "Gambia", "GM", "GMB", 270, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (82, "Georgia", "GE", "GEO", 268, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (83, "Germany", "DE", "DEU", 276, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (84, "Ghana", "GH", "GHA", 288, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (85, "Gibraltar", "GI", "GIB", 292, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (86, "Greece", "GR", "GRC", 300, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (87, "Greenland", "GL", "GRL", 304, 3, 13);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (88, "Grenada", "GD", "GRD", 308, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (89, "Guadeloupe", "GP", "GLP", 312, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (90, "Guam", "GU", "GUM", 316, 4, 16);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (91, "Guatemala", "GT", "GTM", 320, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (92, "Guernsey", "GG", "GGY", 831, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (93, "Guinea", "GN", "GIN", 324, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (94, "Guinea-Bissau", "GW", "GNB", 624, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (95, "Guyana", "GY", "GUY", 328, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (96, "Haiti", "HT", "HTI", 332, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (97, "Heard Island and McDonald Islands", "HM", "HMD", 334, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (98, "Holy See", "VA", "VAT", 336, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (99, "Honduras", "HN", "HND", 340, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (100, "Hong Kong", "HK", "HKG", 344, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (101, "Hungary", "HU", "HUN", 348, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (102, "Iceland", "IS", "ISL", 352, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (103, "India", "IN", "IND", 356, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (104, "Indonesia", "ID", "IDN", 360, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (105, "Iran (Islamic Republic of)", "IR", "IRN", 364, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (106, "Iraq", "IQ", "IRQ", 368, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (107, "Ireland", "IE", "IRL", 372, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (108, "Isle of Man", "IM", "IMN", 833, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (109, "Israel", "IL", "ISR", 376, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (110, "Italy", "IT", "ITA", 380, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (111, "Jamaica", "JM", "JAM", 388, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (112, "Japan", "JP", "JPN", 392, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (113, "Jersey", "JE", "JEY", 832, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (114, "Jordan", "JO", "JOR", 400, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (115, "Kazakhstan", "KZ", "KAZ", 398, 2, 2);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (116, "Kenya", "KE", "KEN", 404, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (117, "Kiribati", "KI", "KIR", 296, 4, 16);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (118, "Korea (Democratic People's Republic of)", "KP", "PRK", 408, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (119, "Korea (Republic of)", "KR", "KOR", 410, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (120, "Kuwait", "KW", "KWT", 414, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (121, "Kyrgyzstan", "KG", "KGZ", 417, 2, 2);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (122, "Lao People's Democratic Republic", "LA", "LAO", 418, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (123, "Latvia", "LV", "LVA", 428, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (124, "Lebanon", "LB", "LBN", 422, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (125, "Lesotho", "LS", "LSO", 426, 1, 1);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (126, "Liberia", "LR", "LBR", 430, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (127, "Libya", "LY", "LBY", 434, 1, 20);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (128, "Liechtenstein", "LI", "LIE", 438, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (129, "Lithuania", "LT", "LTU", 440, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (130, "Luxembourg", "LU", "LUX", 442, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (131, "Macao", "MO", "MAC", 446, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (132, "Macedonia (the former Yugoslav Republic of)", "MK", "MKD", 807, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (133, "Madagascar", "MG", "MDG", 450, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (134, "Malawi", "MW", "MWI", 454, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (135, "Malaysia", "MY", "MYS", 458, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (136, "Maldives", "MV", "MDV", 462, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (137, "Mali", "ML", "MLI", 466, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (138, "Malta", "MT", "MLT", 470, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (139, "Marshall Islands", "MH", "MHL", 584, 4, 16);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (140, "Martinique", "MQ", "MTQ", 474, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (141, "Mauritania", "MR", "MRT", 478, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (142, "Mauritius", "MU", "MUS", 480, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (143, "Mayotte", "YT", "MYT", 175, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (144, "Mexico", "MX", "MEX", 484, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (145, "Micronesia (Federated States of)", "FM", "FSM", 583, 4, 16);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (146, "Moldova (Republic of)", "MD", "MDA", 498, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (147, "Monaco", "MC", "MCO", 492, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (148, "Mongolia", "MN", "MNG", 496, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (149, "Montenegro", "ME", "MNE", 499, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (150, "Montserrat", "MS", "MSR", 500, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (151, "Morocco", "MA", "MAR", 504, 1, 20);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (152, "Mozambique", "MZ", "MOZ", 508, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (153, "Myanmar", "MM", "MMR", 104, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (154, "Namibia", "NA", "NAM", 516, 1, 1);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (155, "Nauru", "NR", "NRU", 520, 4, 16);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (156, "Nepal", "NP", "NPL", 524, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (157, "Netherlands", "NL", "NLD", 528, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (158, "New Caledonia", "NC", "NCL", 540, 4, 22);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (159, "New Zealand", "NZ", "NZL", 554, 4, 10);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (160, "Nicaragua", "NI", "NIC", 558, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (161, "Niger", "NE", "NER", 562, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (162, "Nigeria", "NG", "NGA", 566, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (163, "Niue", "NU", "NIU", 570, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (164, "Norfolk Island", "NF", "NFK", 574, 4, 10);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (165, "Northern Mariana Islands", "MP", "MNP", 580, 4, 16);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (166, "Norway", "NO", "NOR", 578, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (167, "Oman", "OM", "OMN", 512, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (168, "Pakistan", "PK", "PAK", 586, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (169, "Palau", "PW", "PLW", 585, 4, 16);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (170, "Palestine", "PS", "PSE", 275, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (171, "Panama", "PA", "PAN", 591, 3, 8);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (172, "Papua New Guinea", "PG", "PNG", 598, 4, 22);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (173, "Paraguay", "PY", "PRY", 600, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (174, "Peru", "PE", "PER", 604, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (175, "Philippines", "PH", "PHL", 608, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (176, "Pitcairn", "PN", "PCN", 612, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (177, "Poland", "PL", "POL", 616, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (178, "Portugal", "PT", "PRT", 620, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (179, "Puerto Rico", "PR", "PRI", 630, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (180, "Qatar", "QA", "QAT", 634, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (181, "union", "RE", "REU", 638, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (182, "Romania", "RO", "ROU", 642, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (183, "Russian Federation", "RU", "RUS", 643, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (184, "Rwanda", "RW", "RWA", 646, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (185, "Saint Barthelemy", "BL", "BLM", 652, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (186, "Saint Helena Ascension and Tristan da Cunha", "SH", "SHN", 654, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (187, "Saint Kitts and Nevis", "KN", "KNA", 659, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (188, "Saint Lucia", "LC", "LCA", 662, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (189, "Saint Martin (French part)", "MF", "MAF", 663, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (190, "Saint Pierre and Miquelon", "PM", "SPM", 666, 3, 13);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (191, "Saint Vincent and the Grenadines", "VC", "VCT", 670, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (192, "Samoa", "WS", "WSM", 882, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (193, "San Marino", "SM", "SMR", 674, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (194, "Sao Tome and Principe", "ST", "STP", 678, 1, 6);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (195, "Saudi Arabia", "SA", "SAU", 682, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (196, "Senegal", "SN", "SEN", 686, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (197, "Serbia", "RS", "SRB", 688, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (198, "Seychelles", "SC", "SYC", 690, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (199, "Sierra Leone", "SL", "SLE", 694, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (200, "Singapore", "SG", "SGP", 702, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (201, "Sint Maarten (Dutch part)", "SX", "SXM", 534, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (202, "Slovakia", "SK", "SVK", 703, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (203, "Slovenia", "SI", "SVN", 705, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (204, "Solomon Islands", "SB", "SLB", 90, 4, 22);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (205, "Somalia", "SO", "SOM", 706, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (206, "South Africa", "ZA", "ZAF", 710, 1, 1);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (207, "South Georgia and the South Sandwich Islands", "GS", "SGS", 239, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (208, "South Sudan", "SS", "SSD", 728, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (209, "Spain", "ES", "ESP", 724, 5, 11);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (210, "Sri Lanka", "LK", "LKA", 144, 2, 4);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (211, "Sudan", "SD", "SDN", 729, 1, 20);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (212, "Suriname", "SR", "SUR", 740, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (213, "Svalbard and Jan Mayen", "SJ", "SJM", 744, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (214, "Swaziland", "SZ", "SWZ", 748, 1, 1);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (215, "Sweden", "SE", "SWE", 752, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (216, "Switzerland", "CH", "CHE", 756, 5, 7);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (217, "Syrian Arab Republic", "SY", "SYR", 760, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (218, "Taiwan Province of China", "TW", "TWN", 158, 2, 12);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (219, "Tajikistan", "TJ", "TJK", 762, 2, 2);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (220, "Tanzania", "TZ", "TZA", 834, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (221, "Thailand", "TH", "THA", 764, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (222, "Timor-Leste", "TL", "TLS", 626, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (223, "Togo", "TG", "TGO", 768, 1, 14);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (224, "Tokelau", "TK", "TKL", 772, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (225, "Tonga", "TO", "TON", 776, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (226, "Trinidad and Tobago", "TT", "TTO", 780, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (227, "Tunisia", "TN", "TUN", 788, 1, 20);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (228, "Turkey", "TR", "TUR", 792, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (229, "Turkmenistan", "TM", "TKM", 795, 2, 2);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (230, "Turks and Caicos Islands", "TC", "TCA", 796, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (231, "Tuvalu", "TV", "TUV", 798, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (232, "Uganda", "UG", "UGA", 800, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (233, "Ukraine", "UA", "UKR", 804, 5, 15);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (234, "United Arab Emirates", "AE", "ARE", 784, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (235, "United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", 826, 5, 17);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (236, "United States of America", "US", "USA", 840, 3, 13);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (237, "United States Minor Outlying Islands", "UM", "UMI", 581, NULL, NULL);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (238, "Uruguay", "UY", "URY", 858, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (239, "Uzbekistan", "UZ", "UZB", 860, 2, 2);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (240, "Vanuatu", "VU", "VUT", 548, 4, 22);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (241, "Venezuela (Bolivarian Republic of)", "VE", "VEN", 862, 3, 3);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (242, "Viet Nam", "VN", "VNM", 704, 2, 21);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (243, "Virgin Islands (British)", "VG", "VGB", 92, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (244, "Virgin Islands (U.S.)", "VI", "VIR", 850, 3, 19);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (245, "Wallis and Futuna", "WF", "WLF", 876, 4, 18);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (246, "Western Sahara", "EH", "ESH", 732, 1, 20);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (247, "Yemen", "YE", "YEM", 887, 2, 9);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (248, "Zambia", "ZM", "ZMB", 894, 1, 5);
INSERT INTO dw.Country (idCountry, country_name, alpha_2, alpha_3, code, idContinent, idRegion) VALUES (249, "Zimbabwe", "ZW", "ZWE", 716, 1, 5);
