INSERT INTO dw.Region (idRegion, region_name) VALUES (1, "Southern Africa");
INSERT INTO dw.Region (idRegion, region_name) VALUES (2, "Central Asia");
INSERT INTO dw.Region (idRegion, region_name) VALUES (3, "South America");
INSERT INTO dw.Region (idRegion, region_name) VALUES (4, "Southern Asia");
INSERT INTO dw.Region (idRegion, region_name) VALUES (5, "Eastern Africa");
INSERT INTO dw.Region (idRegion, region_name) VALUES (6, "Middle Africa");
INSERT INTO dw.Region (idRegion, region_name) VALUES (7, "Western Europe");
INSERT INTO dw.Region (idRegion, region_name) VALUES (8, "Central America");
INSERT INTO dw.Region (idRegion, region_name) VALUES (9, "Western Asia");
INSERT INTO dw.Region (idRegion, region_name) VALUES (10, "Australia and New Zealand");
INSERT INTO dw.Region (idRegion, region_name) VALUES (11, "Southern Europe");
INSERT INTO dw.Region (idRegion, region_name) VALUES (12, "Eastern Asia");
INSERT INTO dw.Region (idRegion, region_name) VALUES (13, "Northern America");
INSERT INTO dw.Region (idRegion, region_name) VALUES (14, "Western Africa");
INSERT INTO dw.Region (idRegion, region_name) VALUES (15, "Eastern Europe");
INSERT INTO dw.Region (idRegion, region_name) VALUES (16, "Micronesia");
INSERT INTO dw.Region (idRegion, region_name) VALUES (17, "Northern Europe");
INSERT INTO dw.Region (idRegion, region_name) VALUES (18, "Polynesia");
INSERT INTO dw.Region (idRegion, region_name) VALUES (19, "Caribbean");
INSERT INTO dw.Region (idRegion, region_name) VALUES (20, "Northern Africa");
INSERT INTO dw.Region (idRegion, region_name) VALUES (21, "South-Eastern Asia");
INSERT INTO dw.Region (idRegion, region_name) VALUES (22, "Melanesia");
